export default function ExecutiveSummary() {
  return (
    <section id="summary" className="py-12 border-t border-[#E2DDD6] scroll-mt-20">
      <div className="flex items-baseline justify-between mb-6">
        <h2 className="font-serif text-black" style={{ fontSize: "clamp(1.8rem, 3vw, 2.5rem)" }}>
          Executive Summary
        </h2>
        <span className="label-caps">Section 04 / Analyst Memo</span>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-[1fr_280px] gap-8">
        {/* Drop-cap placeholder */}
        <div>
          <div className="border border-dashed border-[#E2DDD6] bg-[#FAF7F2] p-6 rounded-none">
            <p className="label-caps mb-3 text-[#C4BFB8]">Placeholder — sourced from Telegram + X</p>
            <p className="font-sans text-[13px] text-[#999] leading-relaxed italic">
              Executive summary narrative will be generated by scraping the Omnipair Telegram
              channel and X account for recent product updates, team commentary, and growth signals.
              This section will cover protocol positioning, key milestones, and the analyst thesis.
            </p>
          </div>
        </div>

        {/* Sidebars */}
        <div className="space-y-4">
          <div className="border border-[#E2DDD6] p-4">
            <p className="label-caps mb-3">What&apos;s Interesting</p>
            <ul className="space-y-2">
              {[
                "Permissionless long-tail asset support — no whitelist or governance vote required",
                "GAMM architecture unifies spot trading and lending in a single pool",
                "63 liquidations processed without incident across ~90 days of mainnet operation",
                "4.02× spot/NAV premium reflects strong market conviction above treasury backing",
              ].map((item, i) => (
                <li key={i} className="flex gap-2 font-sans text-[12px] text-[#444] leading-relaxed">
                  <span className="text-[#D4B596] mt-0.5 shrink-0">–</span>
                  {item}
                </li>
              ))}
            </ul>
          </div>

          <div className="border border-[#E2DDD6] p-4">
            <p className="label-caps mb-3">What to Watch</p>
            <ul className="space-y-2">
              {[
                "Protocol revenue currently $0 — fee accrual has not yet started",
                "Spot premium at 301% above NAV — elevated relative to treasury backing",
                "7.8 months runway at $50K/mo burn — raises question of next capital event",
                "OMFG-005 live: strategic OTC raise vote in progress",
              ].map((item, i) => (
                <li key={i} className="flex gap-2 font-sans text-[12px] text-[#444] leading-relaxed">
                  <span className="text-[#FF6477] mt-0.5 shrink-0">–</span>
                  {item}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </section>
  );
}
